### ISSUE TITLE
NullPointerException Ballooning Log File Size

### ISSUE THREAD

**Issue by Nouser** [a-h-designs/Advanced-Mining#4]
Hey there,

Someone in my clan had a huge log file getting written, 10MB a minute or so, because of a persistent NPE.

```2024-05-08 00:58:58 EEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
at com.advancedmining.AdvancedMiningAdditionalOverlay.render(AdvancedMiningAdditionalOverlay.java:40)
at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:511)
at je.bz(je.java:3211)
at je.aw(je.java:122)
at kp.ix(kp.java:4943)
at aa.le(aa.java:10786)
at aa.le(aa.java:10817)
at et.lp(et.java:10681)
at client.xz(client.java:4660)
at client.bs(client.java:1204)
at bx.am(bx.java:410)
at bx.lo(bx.java)
at bx.run(bx.java:58205)
at java.base/java.lang.Thread.run(Unknown Source)
2024-05-08 00:58:58 EEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
at com.advancedmining.AdvancedMiningGemsOverlay.render(AdvancedMiningGemsOverlay.java:40)
at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:511)
at je.bz(je.java:3211)
at je.aw(je.java:122)
at kp.ix(kp.java:4943)
at aa.le(aa.java:10786)
at aa.le(aa.java:10817)
at et.lp(et.java:10681)
at client.xz(client.java:4660)
at client.bs(client.java:1204)
at bx.am(bx.java:410)
at bx.lo(bx.java)
at bx.run(bx.java:58205)
at java.base/java.lang.Thread.run(Unknown Source)
```
This continued on, making a new log file when it got to 10MB and filling up all his spare space. I'm not sure about how to repro, but I hope this can help. They had all default settings for the plugin.

**Comment by a-h-designs** [comment]
Sorry it's taken a while to get to this. I am looking into it and trying to figure a way to make it not error and log it.

**Comment by a-h-designs** [comment]
I have managed to identify the issue and hopefully I have fixed it as in testing it doesn't show me any errors or logs. I will upload the fix very soon and thank you for bringing this to my intention.
