### ISSUE TITLE
Runelite Crash 

### ISSUE THREAD

**Issue by kulcris** [a-h-designs/Advanced-Mining#6]
I'm getting this error thousands of times in a row

```
java.lang.ArrayIndexOutOfBoundsException: null
2024-08-22 07:26:30 CDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.advancedmining.AdvancedMiningPlugin.onGameTick(AdvancedMiningPlugin.java:210)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:220)
	at client.hm(client.java:17068)
	at client.bp(client.java)
	at bx.az(bx.java:366)
	at bx.kj(bx.java)
	at bx.run(bx.java:22397)
	at java.base/java.lang.Thread.run(Unknown Source)
```
	
	
It may or may not be related to a crash I get every so often. 

Crash normally happens when i resize the window or move it to another screen, It is also random.

**Comment by a-h-designs** [comment]
I've had a look at the error and the line it seems to point to is checking your inventory. So it could be a problem because of the crash you get. I will leave it open for now, but let me know if it happens again and I'll take a look at it again.
